library("optparse")

option_list = list(
  make_option(c("--eigenvec"), type="character", default=NULL, 
              help="Eigenvector file generated by plink", metavar="character"),
  make_option(c("--phenotype"), type="character", default=NULL,
              help="Phenotype file for grouping", metavar="character"),
  make_option(c("--iid"), type="character", default=NULL,
              help="IID column in the phenotype file", metavar="character"),
  make_option(c("-o", "--out"), type="character", default=NULL,
              help="Output file", metavar="character")
)
opt_parser <- OptionParser(option_list=option_list);
opt <- parse_args(opt_parser);

eigenvec <- read.table(opt$eigenvec,header=F)
n_pcs <- length(eigenvec) - 2
eigenvec_cols <- c(c("FID", "IID"),sapply(seq(1:n_pcs),function(x) paste("PC",x,sep="")))
colnames(eigenvec) <- eigenvec_cols

#Read phenotype file
phenotype <- read.csv(opt$phenotype)

#Merge eigenvector and phenotype file
data <- merge(eigenvec,phenotype,by.x="IID",by.y=opt$iid)
cols <- setdiff(colnames(data), c('FID','IID'))
data<-data[,c(c('FID','IID'),cols)]
write.table(data,file=opt$out,row.names = FALSE, quote=FALSE)
