library("optparse")

option_list = list(
  make_option(c("-i", "--input"), type="character", default=NULL, 
              help="Eigenvalue file generated by plink", metavar="character"),
  make_option(c("-o", "--out"), type="character", default="scree_plot.png", 
              help="Path of the scree plot png file [default= %default]", metavar="character")
); 

opt_parser <- OptionParser(option_list=option_list);
opt <- parse_args(opt_parser);

eigenvals <- scan(opt$input)
#Scree Plot
png(opt$out,width=1024,height=768)
plot(
    x = seq(1:length(eigenvals)), y = eigenvals,
    type = "o",
    xlab = "Principle Component", ylab = "Variance");
dev.off()